Repository shravan20/flare.ts, pull requests merged in 2023-10, with the labels that each got.

#17 feat: Added new Array Util methods
  lib/sample.ts
  lib/tests/ArrayUtils/test.spec.ts
  lib/utility/ArrayUtils/index.d.ts
  lib/utility/ArrayUtils/index.ts
  mocha.opts
  package-lock.json
  package.json
  tests/test.spec.ts
Labels: good first issue, hacktoberfest, hacktobestfest-accepted, hacktoberfest2023, medium

#20 feat: added array utils
  lib/tests/ArrayUtils/test.spec.ts
  lib/utility/ArrayUtils/index.ts
  package.json
Labels: enhancement, good first issue, hacktoberfest, hacktobestfest-accepted, hacktoberfest2023, medium, easy

#25 JSON Comparison
  lib/tests/JSONUtils/test.spec.ts
  lib/utility/JSONUtils/index.ts
  package-lock.json
Labels: enhancement, help wanted, good first issue, hacktoberfest, hacktobestfest-accepted, large, good-first-issue

#29 feat: date-time utils
  .npmignore
  .vscode/extensions.json
  lib/tests/DateUtils/test.spec.ts
  lib/tests/JSONUtils/test.spec.ts
  lib/utility/DateUtils/index.ts
  package-lock.json
  package.json
  settings.json
Labels: enhancement, good first issue, hacktoberfest, medium, easy, good-first-issue
